// Ficha técnica declarativa: cada campo diz seu próprio tipo/unidade/helper,
// e a UI (MUI TextField) é gerada a partir disso — não há HTML hardcoded por campo.

export const CONFIG_FIELDS = [
  "tank-dims", "tank-volume-gross", "tank-volume-net", "tank-water-level", "tank-material", "tank-glass-thickness", "tank-brand", "tank-setup-date", "tank-cycling-date",
  "sump-dims", "sump-volume", "sump-volume-operation", "sump-chambers", "sump-chamber-detail", "sump-glass-thickness", "sump-pump-model", "sump-pump-flow", "sump-pump-flow-real", "sump-mech-media", "sump-bio-media",
  "hyd-downpipe-diameter", "hyd-return-head", "hyd-turnover", "hyd-wavemaker", "hyd-antisiphon", "hyd-notes",
  "eq-heater", "eq-lighting", "eq-extra-pumps", "eq-co2", "eq-controller", "eq-other",
  "sub-substrate", "sub-hardscape", "sub-plants",
  "maint-percent", "maint-frequency", "maint-media-frequency",
  "struct-weight", "struct-load", "struct-notes",
  "fauna-notes",
  "notes",
  "hyd-antisiphon-done",
];

export const CONFIG_SPEC = [
  { title: "Aquário principal", eyebrow: "Display", fields: [
    { id: "tank-dims", label: "Dimensões", type: "text", ph: "200 × 50 × 70", helper: "Comprimento × largura × altura, em centímetros." },
    { id: "tank-volume-gross", label: "Volume bruto", type: "number", step: "0.1", unit: "L", ph: "700", helper: "C × L × A. É o número do catálogo — não use para dosagem." },
    { id: "tank-volume-net", label: "Volume líquido", type: "number", step: "0.1", unit: "L", ph: "597,5", helper: "Já descontando substrato, rochas e borda livre. É por este que se dosa." },
    { id: "tank-water-level", label: "Lâmina d'água", type: "number", step: "0.5", unit: "cm", ph: "65", helper: "Da base até a superfície.", est: true },
    { id: "tank-material", label: "Material", type: "text", ph: "Vidro", helper: "Vidro comum, temperado ou acrílico." },
    { id: "tank-glass-thickness", label: "Espessura do vidro", type: "number", step: "0.5", unit: "mm", ph: "15", helper: "Para 70 cm de coluna, o recomendado é 15–19 mm.", est: true },
    { id: "tank-brand", label: "Fabricante", type: "text", ph: "—", helper: "Útil para garantia e para revenda." },
    { id: "tank-setup-date", label: "Início do projeto", type: "text", ph: "Nov/2025", helper: "Quando o aquário foi montado." },
    { id: "tank-cycling-date", label: "Início da ciclagem", type: "text", ph: "Dez/2025", helper: "Quando a colônia bacteriana começou a se formar." },
  ]},
  { title: "Sump", eyebrow: "A várzea", fields: [
    { id: "sump-dims", label: "Dimensões externas", type: "text", ph: "94 × 34 × 34", helper: "Comprimento × largura × altura, em centímetros." },
    { id: "sump-volume", label: "Volume bruto", type: "number", step: "0.1", unit: "L", ph: "108,7", helper: "Capacidade total até a borda." },
    { id: "sump-volume-operation", label: "Volume em operação", type: "number", step: "0.1", unit: "L", ph: "79,1", helper: "No nível de trabalho de 25 cm. A diferença é a folga anti-transbordo." },
    { id: "sump-chambers", label: "Número de câmaras", type: "number", step: "1", ph: "3", helper: "Decantação, biológica e retorno." },
    { id: "sump-chamber-detail", label: "Detalhe das câmaras", type: "text", wide: true, ph: "C1 Decantação 39cm · C2 Biológica 10cm · C3 Retorno 44cm", helper: "Comprimento e volume útil de cada câmara." },
    { id: "sump-glass-thickness", label: "Espessura do vidro", type: "number", step: "0.5", unit: "mm", ph: "8", helper: "Sump raso exige menos que o display.", est: true },
    { id: "sump-pump-model", label: "Bomba de retorno", type: "text", ph: "Oceantech 9000 L/h", helper: "Marca e modelo." },
    { id: "sump-pump-flow", label: "Vazão nominal", type: "number", step: "1", unit: "L/h", ph: "9000", helper: "Valor de catálogo, medido sem altura nem tubulação." },
    { id: "sump-pump-flow-real", label: "Vazão real", type: "number", step: "1", unit: "L/h", ph: "5000", helper: "Depois das perdas de altura e curvas. É o que define o turnover." },
    { id: "sump-mech-media", label: "Mídia mecânica", type: "text", ph: "Manta de perlon (34 × 39 cm)", helper: "Retém sólidos. Trocar a cada 10–14 dias." },
    { id: "sump-bio-media", label: "Mídia biológica", type: "text", ph: "Quartzite Glass 10 L + cerâmicas", helper: "Abriga a colônia. Alvo para a carga adulta: 12–18 L." },
  ]},
  { title: "Hidráulica e segurança", eyebrow: "A correnteza", fields: [
    { id: "hyd-downpipe-diameter", label: "Diâmetro da descida", type: "text", wide: true, ph: "medir", helper: "Diâmetro interno em mm. Define o teto real de vazão de todo o sistema — abaixo de 50 mm a bomba precisa de registro.", critical: true },
    { id: "hyd-return-head", label: "Altura manométrica", type: "text", unit: "m", ph: "1,2–1,4", helper: "Desnível do sump até o bocal de retorno.", est: true },
    { id: "hyd-turnover", label: "Turnover", type: "text", ph: "7,3×/h", helper: "Renovações por hora. Faixa ideal para ciclídeo grande: 5–10×/h." },
    { id: "hyd-wavemaker", label: "Wave maker", type: "text", wide: true, ph: "15 W, fluxo cruzado", helper: "Circulação interna, somada ao retorno. Evita zona morta em 2 m de comprimento." },
    { id: "hyd-antisiphon", label: "Furo anti-sifão", type: "text", wide: true, ph: "Pendente", helper: "Observações sobre a execução. O estado atual é definido no capítulo 4." },
    { id: "hyd-notes", label: "Teste de queda de energia", type: "textarea", wide: true, ph: "Desligue a bomba na tomada e anote onde o nível estabiliza no sump.", helper: "É o único jeito de validar os cálculos de cheia." },
  ]},
  { title: "Equipamentos", eyebrow: "Instalado", fields: [
    { id: "eq-heater", label: "Aquecedor", type: "text", wide: true, ph: "Nenhum instalado", helper: "Recomendado: 2 × 300 W na C3 com termostato externo. Nunca um único 1.000 W." },
    { id: "eq-lighting", label: "Iluminação", type: "text", ph: "LED full spectrum", helper: "Modelo e fotoperíodo. O alvo é 8 h fixas no timer." },
    { id: "eq-extra-pumps", label: "Bombas adicionais", type: "text", ph: "Wave maker 15 W", helper: "Tudo que movimenta água além do retorno." },
    { id: "eq-co2", label: "CO₂", type: "text", ph: "Não utilizado", helper: "Injeção de CO₂ derruba o pH — atenção redobrada com KH baixo." },
    { id: "eq-controller", label: "Controlador", type: "text", ph: "Termostato externo", helper: "Sensor no display, não no sump." },
    { id: "eq-other", label: "Outros", type: "text", ph: "—", helper: "UV, ozônio, doseadora, o que mais houver." },
  ]},
  { title: "Substrato e decoração", eyebrow: "O leito", fields: [
    { id: "sub-substrate", label: "Substrato", type: "text", ph: "Areia N00 (~50 L)", helper: "Tipo e volume. Desloca cerca de 65% do próprio volume em água." },
    { id: "sub-hardscape", label: "Rochas e troncos", type: "text", ph: "MixRock + Sansibar (~20 L)", helper: "Colunas verticais quebram a linha de visão entre territórios." },
    { id: "sub-plants", label: "Plantas", type: "text", wide: true, ph: "—", helper: "Espécies e localização. Ciclídeos grandes costumam desenterrar." },
  ]},
  { title: "Manutenção", eyebrow: "O calendário das águas", fields: [
    { id: "maint-percent", label: "TPA por troca", type: "number", step: "1", unit: "%", ph: "33", helper: "Percentual do volume do sistema trocado de cada vez." },
    { id: "maint-frequency", label: "Frequência da TPA", type: "text", ph: "Semanal ou quinzenal", helper: "Prepare a água 24 h antes: aeração, declorador e bicarbonato." },
    { id: "maint-media-frequency", label: "Troca de mídia", type: "text", wide: true, ph: "Perlon 10–14 dias · carvão 4–6 semanas", helper: "Perlon vencido deixa de remover sólidos e vira fonte de nitrato." },
  ]},
  { title: "Carga estrutural", eyebrow: "Sobre a laje", fields: [
    { id: "struct-weight", label: "Peso total do sistema", type: "text", wide: true, ph: "≈ 1.069 kg", helper: "Água, substrato, rocha, vidro e móvel somados." },
    { id: "struct-load", label: "Carga por m²", type: "text", wide: true, ph: "≈ 951 kg/m²", helper: "A NBR 6120 prevê 150–200 kg/m² para piso residencial." },
    { id: "struct-notes", label: "Notas estruturais", type: "textarea", wide: true, ph: "Posicionamento, orientação do eixo, avaliação de engenheiro, regimento do condomínio.", helper: "Encostar em parede estrutural e deixar o eixo perpendicular ao vão da laje." },
  ]},
  { title: "Fauna", eyebrow: "Os habitantes", fields: [
    { id: "fauna-notes", label: "Espécies e biometria", type: "textarea", wide: true, rows: 5, ph: "Espécie, quantidade, tamanho atual e adulto, observações de compatibilidade.", helper: "Some o tamanho adulto, não o atual — é ele que define se o sistema cabe." },
  ]},
  { title: "Notas gerais", eyebrow: "Diário do sistema", fields: [
    { id: "notes", label: "Histórico de mudanças", type: "textarea", wide: true, rows: 4, ph: "Ajustes de hidráulica, problemas resolvidos, trocas de equipamento…", helper: "Campo livre. Entra no export JSON junto com o resto." },
  ]},
];

export const DEFAULT_CONFIG = {
  "tank-dims": "200 × 50 × 70",
  "tank-volume-gross": 700,
  "tank-volume-net": 597.5,
  "tank-water-level": 65,
  "tank-material": "Vidro",
  "tank-glass-thickness": 15,
  "tank-brand": "",
  "tank-setup-date": "Nov/2025",
  "tank-cycling-date": "Dez/2025",
  "sump-dims": "94 × 34 × 34",
  "sump-volume": 108.7,
  "sump-volume-operation": 79.1,
  "sump-chambers": 3,
  "sump-chamber-detail": "C1 Decantação 39cm (33,2L) · C2 Biológica 10cm (8,5L) · C3 Retorno 44cm (37,4L)",
  "sump-glass-thickness": 8,
  "sump-pump-model": "Oceantech 9000 L/h",
  "sump-pump-flow": 9000,
  "sump-pump-flow-real": 5000,
  "sump-mech-media": "Manta de perlon (34×39cm)",
  "sump-bio-media": "Quartzite Glass 10L + cerâmicas adicionais",
  "hyd-downpipe-diameter": "",
  "hyd-return-head": "1,2–1,4",
  "hyd-turnover": "7,3–8,4×/h",
  "hyd-wavemaker": "15W, fluxo cruzado [EST] 6.000–9.000 L/h",
  "hyd-antisiphon": "Pendente — furar 3–4mm abaixo da linha d'água",
  "hyd-notes": "",
  "eq-heater": "Nenhum instalado — recomendado 2× 300W em C3 + termostato externo",
  "eq-lighting": "",
  "eq-extra-pumps": "Wave maker 15W (fluxo cruzado)",
  "eq-co2": "Não utilizado",
  "eq-controller": "Termostato externo (recomendado, ainda não instalado)",
  "eq-other": "",
  "sub-substrate": "Areia N00 (~50L)",
  "sub-hardscape": "MixRock + Sansibar (~20L)",
  "sub-plants": "",
  "maint-percent": 33,
  "maint-frequency": "Semanal ou quinzenal (33% = 225L)",
  "maint-media-frequency": "Perlon 10–14 dias · carvão 4–6 semanas · Purigen 4–6 meses",
  "struct-weight": "≈ 1.069 kg (display 951 kg + sump 118 kg)",
  "struct-load": "≈ 951 kg/m² — acima do limite NBR 6120 (150–200 kg/m²)",
  "struct-notes": "Encostar em parede estrutural, eixo de 2m perpendicular ao vão da laje, avaliar com engenheiro se houver dúvida, verificar regimento do condomínio.",
  "hyd-antisiphon-done": "nao",
  "fauna-notes": "Oscar Bronze 1× (15cm → 30–38cm adulto) · Jack Dempsey Blue 1× (10cm → 20–25cm) · Severum Gold 2× (10 e 6cm → 20–25cm cada) · Lambaris 6× (~5cm → 10–12cm) · Pangasius Albino 1× (10cm → 100–130cm adulto — incompatível com o sistema, planejar realocação em 6–12 meses).",
  notes: "",
};
